### ISSUE TITLE
Type A OPN ring

### ISSUE THREAD

**Issue by philips** [darconeous/gauss-key-card#2]
I noticed NFC ring has a new type A device using a  ntag 216. I can't tell from the spec sheets if it meets all the requirements though. Do you have any advice?

https://store.nfcring.com/products/opn?variant=500586053633

**Comment by darconeous** [comment]
Nope, an NTAG216 won’t cut it. It is not a programmable device. It cannot run programs. It cannot even do basic cryptography.
