### ISSUE TITLE
What about for solokeys?

### ISSUE THREAD

**Issue by nunojpg** [darconeous/gauss-key-card#3]
https://github.com/solokeys/solo/

Since this FIDO2 keys allow to change the firmware, do you think they are capable of running also this applet?

Would be very convenient since I need to carry a key anyway. I guess you to but you might not be able to BYOKey :)

**Comment by darconeous** [comment]
It should be possible to implement the [Tesla Key Card Protocol](https://gist.github.com/darconeous/2cd2de11148e3a75685940158bddf933) on an NFC-supporting Solo key, but `gauss-key-card` is specifically for Javacards—and it looks like the Solo key is not a Javacard.

Luckily the protocol is straightforward and should be easy to implement for someone so inclined.
